### ISSUE TITLE
sniff module opens powershell.exe

### ISSUE THREAD

**Issue by omrirefaeli** [secdev/scapy#1387]
Environment
Scapy version: 2.4.0
Python version: 2.7.12
Operating System: windows 100

when running scapy's module -`Sniff.` a powershell instance is executed.
is there an option to cancel this? I dont see a reason why powershell should be executed. anywho is there a way to go near it that I might not know?
thanks
![image](https://user-images.githubusercontent.com/30568019/39546783-3c12cd52-4e5e-11e8-9920-a2cf5943998f.png)

**Comment by guedou** [comment]
Could you please use the issue template?

**Comment by omrirefaeli** [comment]
is it okay now?

**Comment by gpotter2** [comment]
Hello !
Could you check if https://github.com/secdev/scapy/pull/1394 fixes the bug for you ?
Thanks !

**Comment by omrirefaeli** [comment]
it's nice but doesnt fix the problem, just hides the powershell window.. can't powershell be completely removed and does not even called by scapy? powershell with python as a parent process is not an ordinary thing and with no doubt attract attention if looked for.
thanks :)

**Comment by gpotter2** [comment]
I was able to replicate, and will try to find a fix.

There are no ways, in python, to get low-level informations such as the list of the interfaces, of the machine IP or the IP routes. To access those data, we, depending on the os, call different system calls.

On windows, the most advanced commands require powershell. However, due to its really slow starting time, we use a single sleeping power shell windows for all scapy calls. This is why there is a powershell subprocess.

**Comment by gpotter2** [comment]
This is currently a wontfix.

If you want to use cmd instead of powershell (a cmd will remain open instead of powershell), you can import scapy as the following:
```
from scapy.all import *
POWERSHELL_PROCESS.close()
conf.prog.powershell = None
POWERSHELL_PROCESS.__init__()
# end of import
```
You will still have a cmd windows started in the back ground
