### ISSUE TITLE
[question] Finish and add length of packet in vtp.py

### ISSUE THREAD

**Issue by nikhilh-20** [secdev/scapy#1494]
From #399 ,

Considering the four fixed options in the VTP header: Version, Message Type, Management Domain Length and Management Domain Name (each 1 byte), can the ByteField length be set to 4? Would this be the solution?

 #nikhilh@ubuntu$ uname -a
Linux ubuntu 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I'm using scapy version 2.4.0.dev303

**Comment by gpotter2** [comment]
No. The issue is expecting you to add a `post_build` function that would add edit the packet after being built.

Many other packets use the same trick, for instance https://github.com/secdev/scapy/blob/master/scapy/layers/dns.py#L327 (be careful, the fact that it checks TCP first is specific to DNS, do not copy/paste it as so)

**Comment by guedou** [comment]
Moved to #399
