### ISSUE TITLE
Unneeded ARP resolution with send()

### ISSUE THREAD

**Issue by edgarcosta92** [secdev/scapy#1586]
#### Brief description

Not sure if this is an issue or intended behaviour.  When you send a packet using `send()` it will send an arp request even if the host already knows the MAC address of the IP destination.

#### Environment

- Scapy version: 2.4.0
- Python version: 2.7.12
- Operating System: Ubuntu 16.04.05

#### How to reproduce
```
pkt = IP(dst=dstAddr) 
send(pkt, iface=intf)
```

#### Actual result

Send function will start an ARP resolution process although the host ARP table already has an entry for the destination IP.

#### Expected result

When the IP to MAC is known, send should not resolve again (or at least this should be optional).

**Comment by p-l-** [comment]
When you say "even if the host already knows the MAC address of the IP destination", are you talking about the host's ARP table? If so, that is not an issue since Scapy maintains its own table (see `conf.netcache`).

If you do that `send()` call twice, Scapy should only do the ARP resolution once. If that is not the case, it is a bug.

**Comment by edgarcosta92** [comment]
Yes I meant the host's ARP table. 

And yes, I realized that scapy does the ARP resolution once. Is there a way to force scapy to  use the host's ARP tale instead of its own ? I have a network where I can not broadcast ARP messages, instead I populate host's ARP tables manually.

**Comment by p-l-** [comment]
Nope, not that I know of.
