### ISSUE TITLE
New ISO-TP implementation, consistent constructors

### ISSUE THREAD

**Issue by akorb** [secdev/scapy#1592]
```ISOTPSocket``` is set to ```ISOTPSoftSocket``` or ```ISOTPNativeSocket``` at runtime, but they have different constructors. Thus it's difficult to write scripts which works with both.

At least the first parameter should be the same. ```ISOTPSoftSocket``` requires a **socket**, the native counterpart the **name of the interface**.

Simple script to reproduce:
```python
load_contrib('isotp')
ISOTPNativeSocket('can0', sid=0x123, did=0x456) # Works
ISOTPSoftSocket('can0', sid=0x123, did=0x456) # AttributeError
```

@epozzobon

**Comment by polybassa** [comment]
Actually, fixing this is not quite easy. There can be a huge variety of possibilities. The automatic creation of a CANSocket by a string can only be done, if and only if one is using python3 and linux. In all other cases, the constructors for CANSockets would differ to much, since we allow python-can objects here

**Comment by polybassa** [comment]
Fixed as good as possible, for now. I think this issue can be closed.

**Comment by guedou** [comment]
Thanks.
