### ISSUE TITLE
Question about CI logs

### ISSUE THREAD

**Issue by sieben** [secdev/scapy#163]
Should tcpdump be installed in travis.yml? Because this line appears quite a lot:
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
https://travis-ci.org/secdev/scapy/jobs/130214186

If tcpdump is unnecessary maybe a more descriptive warning message would be helpful.

**Comment by p-l-** [comment]
We don't need tcpdump to run the tests (at least for now) but the message matters since you probably need tcpdump to use Scapy.

**Comment by guedou** [comment]
That's a good question. Scapy only needs `tcpdump` to build BPF filter to limit sniffed packets. The [`attach_filter()`](https://github.com/secdev/scapy/blob/56d488b4e6711f645f1e3bb7935d00f4d60806e4/scapy/arch/linux.py#L125) function includes all the magic.

So far, unit tests are not run as root. Therefore, `tcpdump` is not needed.

I am working on some changes to .travis.yml that will allow unit tests to run as root. The main goal is to perform more accurate tests. Therefore, I think that it could be nice to have a PR that will test `either attach_filter(`) or `sniff()`. I will be happy yo review such PR, however due to the way `attach_filter()`, this test is likely to fail with PyPy.
