### ISSUE TITLE
Status of scapy-com & contrib

### ISSUE THREAD

**Issue by Zopieux** [secdev/scapy#164]
There is this [scapy-com repository](https://bitbucket.org/secdev/scapy-com/) on BitBucket that seems deprecated (last commit in 2014) but yet has more features that mainline scapy. I could not find any documentation about the fate of this repository. AFAICT, this is some *communitarian* effort to add more layers/protocols to scapy, but I can't see any documented procedure to have these improvements merged into mainline.

- Is there a plan to eventually port the few additions that are not yet in scapy and then close this fork? Some people are still trying to open new issues and pull requests.
- What's the difference between *scapy-com* and the `contrib/` folder? What is the policy for choosing things that go to `contrib/` and things that go to built-ins?

**Comment by guedou** [comment]
We need to go into Scapy history to answer your questions =)

When the project was hosted on secdev.org, the `scapy-com` repository was used to push new code to Scapy. However, most of these patches were neither tested or reviewed. Hence, the quality of `scapy-com` is sometimes hasardous. During the switch to bitbucket, the `scapy-com `repository was preserved, yet not much used.
We don't think that it is needed anymore, as github PR offers the same functionality.

If you have some specific code in mind that we can merge from `scapy-com`, please open an Issue or a PR. Then, we will deal with it.

@p-l- could you add some text to the bitbucket scapy-com stating that it is deprecated ? Sorry, I don't have time today =/

Concerning `contrib/`, the main goal was to ease merging new protocols, some where not tested, some might not work on every platform. The [scapy.contrib.status](https://github.com/secdev/scapy/search?utf8=%E2%9C%93&q=contrib.status) should reflect the expected behavior. These days, we ask unit tests along with new protocols. Therefore, the quality should be much better.

Concerning the _policy_, @p-l- and I agreed on adding core protocols do `scapy/layers` and less used ones to `scapy/contrib`.

**Comment by Zopieux** [comment]
Thanks for your detailed answer. It would be indeed useful to warn newcomers that `scapy-com` is virtually dead.
