### ISSUE TITLE
TypeError: 'OSError' object is not subscriptable

### ISSUE THREAD

**Issue by jijianwen** [secdev/scapy#1683]
When I running a python script using scapy(v2.4.0) to send large packets, got the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 486, in send
    self.outs.sendto(sx, sdto)
OSError: [Errno 90] Message too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fuzz.py", line 81, in <module>
    main()
  File "./fuzz.py", line 77, in main
    verbose=0)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 302, in send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 276, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 488, in send
    if msg[0] == 22 and len(sx) < conf.min_pkt_size:
TypeError: 'OSError' object is not subscriptable

Please help take a look.

**Comment by gpotter2** [comment]
Hi,

Please share a small and clear example / piece of code (please as small as possible), that reproduces the issue.

Thanks !

**Comment by jijianwen** [comment]
Prepare 2 machines which could ping each other successfully. Running the following program on one machine should be enough.

# python3 reproducer.py -h <peer_ip> <peer_port>

# cat reproducer.py
#! /usr/bin/python

import sys
import getopt
import time
from scapy.all import *

from scapy.layers.sctp import _SCTPChunkParam
from scapy.layers.sctp import sctpchunkparamtypescls
from scapy.layers.sctp import sctpchunkparamtypes

# ipv6 address param malformed
class SCTPChunkParamIPAddr(_SCTPChunkParam, Packet):
    fields_desc = [ ShortEnumField("type", 6, sctpchunkparamtypes),
                            ShortField("len", 4), ]

def main():
    opts, _ = getopt.getopt(sys.argv[1:], "h:p:", ["host", "port"])
    for opt, arg in opts:
        if opt in ("-h", "--host"):
            target_host = arg
        elif opt in ("-p", "--port"):
            target_port = int(arg)

    sctp_header = (IP(dst=target_host, flags="DF")/
        SCTP(sport=RandShort(),dport=target_port,tag=0))

    send(sctp_header / SCTPChunkInit(init_tag = 1,
        a_rwnd = 4096,
        n_out_streams = 5,
        n_in_streams = 5,
        init_tsn = 1,
        params = [SCTPChunkParamIPAddr()]*500))

if __name__ == "__main__":
    main()

Python version installed on my machines - Python 3.6.6
scapy - v2.4.0

**Comment by jijianwen** [comment]
Prepare 2 machines which could ping each other successfully. Running the following program on one machine should be enough.
the command is -  python3 reproducer.py -h <peer_ip> <peer port> 
The content of the reproducer:
`#! /usr/bin/python

import sys
import getopt
import time
from scapy.all import *

from scapy.layers.sctp import _SCTPChunkParam
from scapy.layers.sctp import sctpchunkparamtypescls
from scapy.layers.sctp import sctpchunkparamtypes

class SCTPChunkParamIPAddr(_SCTPChunkParam, Packet):
    fields_desc = [ ShortEnumField("type", 6, sctpchunkparamtypes),
                    ShortField("len", 4), ]

def main():
    opts, _ = getopt.getopt(sys.argv[1:], "h:p:", ["host", "port"])
    for opt, arg in opts:
        if opt in ("-h", "--host"):
            target_host = arg
        elif opt in ("-p", "--port"):
            target_port = int(arg)

    sctp_header = (IP(dst=target_host, flags="DF")/
        SCTP(sport=RandShort(),dport=target_port,tag=0))

    send(sctp_header / SCTPChunkInit(init_tag = 1,
        a_rwnd = 4096,
        n_out_streams = 5,
        n_in_streams = 5,
        init_tsn = 1,
        params = [SCTPChunkParamIPAddr()]*500))

if __name__ == "__main__":
    main()`

**Comment by guedou** [comment]
Thanks for sharing. Could you reduce the issue to 10 lines or so, on a single machine?

**Comment by jijianwen** [comment]
Please set MTU of device 'lo' to be 1500 on Linux system first.
ip link set dev lo mtu 1500
Then run command as below:
python3 reproducer.py -h 127.0.0.1 -p 10000

Don't forget to restore lo mtu to be original value(65536) after testing.

**Comment by guedou** [comment]
Here is a way to reproduce this error:
```
from scapy.all import *
import unittest.mock as mock

@mock.patch("scapy.arch.linux.socket.socket.sendto")
def test_L3PacketSocket_send_python3(mock_sendto):
    mock_sendto.side_effect = OSError(22, 2807)
    l3ps = L3PacketSocket()
    l3ps.send(IP(dst="8.8.8.8")/ICMP())

test_L3PacketSocket_send_python3()
```

In Python3, `OSError` is raised and should be handled slightly differently at https://github.com/secdev/scapy/blob/master/scapy/arch/linux.py#L568. A fix is on the way.

**Comment by kreddkrikk** [comment]
I'm seeing this error after updating to Linux kernel 4.20.0 from 4.19.12.

Kernel version: 4.20.0-arch1-1-ARCH
Python version: 3.7.1-1

After updating to the latest Arch Linux kernel (4.20.0) I can no longer send packets with scapy (version 2.4.0-2) in Python 3. I make the assumption the kernel update is the reason this issue occurred because I successfully sent a packet with scapy in 4.19.12, updated to 4.20.0, rebooted, and could no longer send packets in scapy. I used the following code to send a packet:


`from scapy.all import *
client="192.168.0.100"
server="192.168.0.101"
ip = IP(src=client, dst=server)
tcp = TCP(sport=12345, dport=80, flags="S")
res=send(ip/tcp)`

The error:

`Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/scapy/arch/linux.py", line 486, in send
    self.outs.sendto(sx, sdto)
OSError: [Errno 22] Invalid argument`

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/scapy/sendrecv.py", line 302, in send
    realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python3.7/site-packages/scapy/sendrecv.py", line 276, in __gen_send
    s.send(p)
  File "/usr/lib/python3.7/site-packages/scapy/arch/linux.py", line 488, in send
    if msg[0] == 22 and len(sx) < conf.min_pkt_size:
TypeError: 'OSError' object is not subscriptable`

When checking tcpdump/wireshark, I notice the SYN packet never gets sent. This code worked fine before the kernel update. Also, using sr1 instead of send doesn't throw the exception, but still never sends the packet:

`sr1(ip/tcp)
Begin emission:
...................................... (and so on)`

I can, however, successfully initiate a 3-way handshake with Python 2.7.15-2, but a subsequent HTTP GET request packet never gets sent:

`from scapy.all import *
client='192.168.0.100'
server='192.168.0.101'
ip = IP(src=client, dst=server)
tcp = TCP(sport=12345, dport=80, flags="S")
res = sr1(ip/tcp)
tcp = TCP(sport=12345, dport=80, flags="A", seq=res[TCP].ack, ack=res[TCP].seq+1)
send(ip/tcp)
tcp = TCP(sport=12345, dport=80, flags="A", seq=res[TCP].ack, ack=res[TCP].seq+1)
payload = "GET / HTTP/1.1\r\nHost: " + server + "\r\n\r\n"
res = sr1(ip/tcp/payload)`

Which prints a "Begin emission: ................." after the HTTP GET request and never sends the packet.

**Comment by catshy** [comment]
Hi，
I have the same question while using sendp(),but there is no errno 90 in L2Socket.
umm, why?
@guedou

**Comment by gpotter2** [comment]
Please retry against 2.4.3 or reopen another issue.
