### ISSUE TITLE
MACsec throws no error when decrypting packet using SA with different an and pn parameters

### ISSUE THREAD

**Issue by charelF** [secdev/scapy#1723]
Concerns: https://github.com/secdev/scapy/blob/master/scapy/contrib/macsec.py

#### Brief description

Using MACsecSA, I want to simulate the encryption and decryption of a macsec frame. In this specific example, I want to see if MACsec prevents me from decrypting a packet with an outdated packet number, to see whether it prevents replay attacks. 

#### Environment

-   Scapy version: `2.4.0`
-   Python version: `3.6.3`
-   Operating System: `Windows 10`

#### How to reproduce

```
from scapy.contrib.macsec import *
from scapy.all import *


# create MACsecSA

# our original sa which we use to encrypt the packet
sci = b'\x52\x54\x00\x13\x01\x56\x00\x01'
an = 0
pn = 1
key = b'gG_EqlvD-J4euCPkurDRfx57pqIOyXGr'
icvlen = 16
encrypt = True
send_sci = True
xpn_en = True  
ssci = 0x7A30C118   
salt = b'\xE6\x30\xE8\x1A\x48\xDE\x86\xA2\x1C\x66\xFA\x6D'
sa = MACsecSA(sci, an, pn, key, icvlen, encrypt, send_sci)


# pc 1 

message = b'Hello World!'

# uses sa to encrypt and encap
packet = sa.encap(Ether()/Raw(message))
encryptedPacket = sa.encrypt(packet)


# pc 2

# we create a modified sa: sa2
sci = b'\x52\x54\x00\x13\x01\x56\x00\x01'
an = 2  # different an
pn = 99  # different pn
key = b'gG_EqlvD-J4euCPkurDRfx57pqIOyXGr'
icvlen = 16
encrypt = True
send_sci = True
xpn_en = True  
ssci = 0x7A30C118   
salt = b'\xE6\x30\xE8\x1A\x48\xDE\x86\xA2\x1C\x66\xFA\x6D'
sa2 = MACsecSA(sci, an, pn, key, icvlen, encrypt, send_sci)

# uses sa2 to decrypt and decap
decryptedPacket = sa2.decrypt(encryptedPacket)
message = sa2.decap(decryptedPacket)[Raw].load
print(message)
```

#### Actual result

```b'Hello World!'```

#### Expected result

Some kind of error because the sa I used to decrypt and decap the packet is sa2, and sa2 uses a different association number and a different packet number.

#### Comment

It might be that I implemented something wrong again, but even after reading through the macsec.uts tests, I could not find what I possibly did wrong.

@qsn Maybe you could help decide whether it is an actual bug, a desired result, or an error of my part.

**Comment by g-mahieux** [comment]
You are not doing anything wrong, but what you are observing is consistent with the way it was designed.

Imagine you are building some MACsec application using this framework. Upon receiving a packet, you would use the incoming packet's AN (and other info, such as MAC address) to identify which MACsecSA object to use (sa or sa2). But, by doing "sa2.decrypt(encryptedPacket)", you are deliberately attempting to decrypt that specific packet with that specific SA.
This design pattern leaves some space for manual experimentation and educational purposes, which are of significant importance in the Scapy context. It's not because it's wrong that it does not make sense to support it. :-) 
Pretty much the same idea goes for the PN. The current design does not handle any PN verification, and does not have all the settings "ReplayWindow", "ValidateFrames", "ReplayProtect", etc... of a complete MACsec instance, among other things.

You might want to design a set of higher level classes like "MACsecSADatabase", "MACsecInstance", "MACsecSC", etc... which would do the job of implementing the higher level properties (settings/flags, statistics counters) of the various layers of a MACsec instance (MAC Security Instance, Secure Channels, Security Associations, etc).

Of course that is simply my opinion.

**Comment by charelF** [comment]
Thank you for the answer. From this point of view, it makes sense, you are right.
If I understand correctly, if I want replay attack protection with the current scapy implementation of MACsec, I would need to implement it myself?

**Comment by g-mahieux** [comment]
At this time, yes.
