### ISSUE TITLE
Packet capture on Windows without a kernel driver

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1747]
I found the following example showing that it is possible to sniff on Windows without using an external library: https://github.com/nospaceships/raw-socket-sniffer

@gpotter2 I think that you will enjoy having a look =)

**Comment by gpotter2** [comment]
That could be very nice indeed, but it wouldn’t be python-only:

- we could use the Powershell code, but it said to be very slow
- should we use the C code ? We could pack it as already compiled within scapy, otherwise it would require to have the redistributables pack installed...


In any case, it would require some minor changes to make it pass the packets to scapy rather than in a pcap. I might just the project owners to help with that

**Comment by guedou** [comment]
Can we call the functions from Python using ctypes ? That will be easier.

**Comment by gpotter2** [comment]
Will have a look, sounds like a good idea.

Note to self: also implement `attach_filter` for consistency between platforms

**Comment by gpotter2** [comment]
Actually, it states
```
Since these programs produce PCAP files, and PCAP files include fully formed packets, a fake ethernet header is synthesized for each packet using the all zeros source and destination ethernet addresses.
```

Which means it’s basically a layer 3 socket. We can already do this on windows (it’s not implemented in scapy) using straight python (i need to check but that’s what I recall). So this is not really useful :/

**Comment by guedou** [comment]
Too bad =\

**Comment by p-l-** [comment]
Anyway you mean we could implement an L3ListenSocket in pure Python / Windows?

**Comment by p-l-** [comment]
Yeah I think so!
