### ISSUE TITLE
python 2.7 support

### ISSUE THREAD

**Issue by akorb** [secdev/scapy#1845]
Python 2.7 support will be dropped on 1st January 2020.
See: https://pythonclock.org/
and many huge project will drop the support for 2.7 too,
see: https://python3statement.org/

My question is if you already have a plan for the future of python support in scapy.

Thus this issue is not a bug, but a question. Unfortunately, I'm not able to add the `question` tag while creating this issue.

**Comment by gpotter2** [comment]
That’s a good question.

We have an impressive amount of python 2/3 compatibility fixes, because we handle bytes strings all over the place (as opposed to Unicode), which encoding/decoding isn’t backward compatible :/

A few thoughts:
- We’ll probably get a performance improvement by dropping Python 2.7 (see `compat.py`), and make generally cleaner code
- the GUI depends heavily on IPython. As they’re dropping Python 2.7, we’ll probably follow them
- we need to make an extraordinary stable build before releasing it. Scapy is released very rarely, meaning we often ask the users to use the github build against X issue. The pypi releases are quite good, but not that stable. We would have to schedule it properly (not like 2.4.2...) and stick up to the plan (it was done greatly with 2.4.0). We’ll have to discuss the versioning: 2.5 ? (Let’s avoid Scapy 3 as much as possible for obvious reasons)
- we still have users on Windows XP: https://github.com/secdev/scapy/issues/1309 meaning we have to announce it properly. Dropping Python 2.7 means dropping all windows XP compatibility (which also allows us to remove lots of compatibility patches)

**Comment by guedou** [comment]
I think that we need to aim for supporting Python 2.7 as long as possible, as we did for Python 2.4.

When 2.7 won’t be easily available to perform unit tests on Travis or AppVeyor, we might want to consider dropping it. Similarly, if supporting Python 2.6 and 3.8 (eight) is impossible, we will likely drop it.

**Comment by p-l-** [comment]
Scapy is a tool that can be used in a very large number of situations. Often, you don't get to choose the Python interpreter you have when you run Scapy. So, as @guedou said, we need to keep supporting Python 2.7 as long as we can.

I don't think this should be a problem for our users, since we will continue to support the most recent Python versions.
