### ISSUE TITLE
Inconsistency between python versions with EnumField

### ISSUE THREAD

**Issue by akorb** [secdev/scapy#1886]
Test Class

```python
class Test(Packet): 
     fields_desc=[ 
          ByteEnumField('data', b'', { 1: "known" }) 
     ]
```

Behavior python3:
Class definition works.
`Test()` works as expected.

Behavior python2:
```
[callstack]
KeyError: ''
```

The problem is the empty string and `_EnumField.any2i_one`.
The following shows the same error in python2:
```python
class Test(Packet):
     fields_desc=[
         ByteEnumField('data', 0, { 1: "known" })
     ]
 
p = Test()
p.data = b''
[callstack]
KeyError: ''
```

Same for BitEnumField, ShortEnumField, etc.

**Comment by guedou** [comment]
`ByteEnumField` only accepts an integer value between 0 and 255. I think that throwing this exception is the correct behavior when assigning a different value to the field.

**Comment by akorb** [comment]
I found this while following: https://github.com/secdev/scapy/issues/1861#issuecomment-467901879

> `ByteEnumField` only accepts an integer value between 0 and 255. I think that throwing this exception is the correct behavior when assigning a different value to the field.

If this is the case, shouldn't python3 throw the exception too?

**Comment by gpotter2** [comment]
https://github.com/secdev/scapy/issues/1861#issuecomment-467901879 was about `StrField` and it’s subclasses (such as `PacketField`)

**Comment by guedou** [comment]
In this example, `raw(p)` will fail in Python3 because `b''` is not an integer.

**Comment by akorb** [comment]
> In this example, `raw(p)` will fail in Python3 because `b''` is not an integer.

I think I understand. It's not important that python 2 and python 3 fail at the same spot in the "pipeline", as long as both fail. Is this right?

**Comment by gpotter2** [comment]
We check for strings during the `any2i(_one)` process, that are expected to be keys matching a value in the enum dictionnary. If it's not a string, we assume it's valid data for the EnumField (whatever type it has). That's why it's different between the Python versions.

> I think I understand. It's not important that python 2 and python 3 fail at the same spot in the "pipeline", as long as both fail. Is this right?

We can't check the data type as you can implement your own EnumField with a custom object instead of an int, or  customs `i2m`... that handle your special cases. In this example, as pointed out by guedou, if you provide some incorrect arguments, it will at least fail during build. In most cases, Python 2 and 3 will fail at the same spot, but this is a corner case as explained above.

**Comment by akorb** [comment]
Thanks a lot for the great explanations!
