### ISSUE TITLE
Scapy support

### ISSUE THREAD

**Issue by unguest** [secdev/scapy#1903]
As python 2 will be discontinued in 2020, will scapy totally move to python3 or a python2 version will be released ?

**Comment by p-l-** [comment]
Scapy's support differs from Python support because Scapy is (also) a pentest tool that you may want to run on a server you don't own, that may have an outdated Python version.

So we will probably continue to support Python 2.7 a bit after its discontinuation, if that support is not too hard to maintain (this will highly depend on future Python versions).

Anyway, a release **will** happen before Python 2.7 support is dropped.

Hope this answers your question.

**Comment by unguest** [comment]
Yup totally thanks :+1:
