### ISSUE TITLE
Dot11Encrypted -vs- Dot11WEP

### ISSUE THREAD

**Issue by stryngs** [secdev/scapy#2063]
#### Things to consider

1.  Please check that you are using the latest scapy version, e.g. installed via:

    `pip install --upgrade git+git://github.com/secdev/scapy`

2.  If you are here to ask a question - please check previous issues and online resources, and consider using gitter instead: <https://gitter.im/secdev/scapy>

3.  Please understand that **this is not a forum** but an issue tracker. The following article explains why you should limit questions asked on Github issues: <https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde>

#### Brief description

> describe the main issue in one sentence
> if possible, describe what components / protocols could be affected by the issue (e.g. wrpcap() + IPv6, it is likely this also affects XXX)

#### Environment

-   Scapy version: `scapy version and/or commit-hash`
-   Python version: `e.g. 3.5`
-   Operating System: `e.g. Minix 3.4`

> if needed - further information to get a picture of your setup (e.g. a sketch of your network setup)

#### How to reproduce

> step-by-step explanation or a short script, may reference section 'Related resources'

#### Actual result

> dump results that outline the issue, please format your code

#### Expected result

> describe the expected result and outline the difference to the actual one, could also be a screen shot (e.g. wireshark)

#### Related resources

> traces / sample pcaps (stripped to the relevant frames), related standards, RFCs or other resources

**Comment by stryngs** [comment]
With the current version as of 20 minutes or so ago, Dot11Encrypted does not work for WEP in Python 3.  In Python 2, it still works and shows as Dot11WEP.

![image](https://user-images.githubusercontent.com/12008469/58850659-82707780-865d-11e9-83e1-0d8baf72f445.png)


If I can offer any help in fixing this, I'd be happy to give it a try.  I use the heck out of scapy for 802.11 analysis and I've been looking forward to the Python 3x shift; just have to move slow with the large volumes of code I've got to port.

**Comment by guedou** [comment]
Thanks for reporting this issue. Could you share the faulty frame in hex or pcap?

**Comment by stryngs** [comment]
Hi @guedou,

Attached for your review.
[example.pcap.gz](https://github.com/secdev/scapy/files/3259474/example.pcap.gz)

**Comment by guedou** [comment]
Did you install the Python `cryptography` module? on both Python2 and Python3? This only happens when the module is not installed.

**Comment by stryngs** [comment]
@guedou Out of random curiosity, seeing as how cryptography wasn't installed in Python3 for me, and once installing it, it worked; shouldn't the original code have Errored out?  I see this a lot of times with some of the deeper level functionality within scapy.

I will go to write some code, and then some unforeseen thing happens.  Instead of my code dying like one would expect, I just get unexpected results, not an Error.  It makes for quite the interesting time with debugging and what not.  Is this perhaps how scapy was built?  I've never peered deep into the guts but I imagine it has some try: excepts:?

**Comment by gpotter2** [comment]
> I will go to write some code, and then some unforeseen thing happens. Instead of my code dying like one would expect, I just get unexpected results, not an Error. 

We try to remain dependency-free for the basic usage.
This brings the cool idea that you can natively on all platforms clone the repo, and run it (it's even more true since the recent libpcap-bindings changes).

> It makes for quite the interesting time with debugging and what not. Is this perhaps how scapy was built? I've never peered deep into the guts but I imagine it has some try: excepts:?

It's a lot of work to ensure Scapy properly reports a missing dependency. Indeed, we use some try: except: all over the place, but thats not the only things we use:

- for Python dependencies (cryptography, IPython, cartopy...), it's indeed mostly try:catch. If you have a look at `main.py`, you'll see that we use the features of new IPython versions while remaining compatible with the older ones.
- for external dependencies (Graphviz, PyX dependencies (texlive...), tcpdump), we mostly perform system calls to see if they are included
- (Windows) we'll detect the libpcap wrapper (Nocap/Winpcap) ans enable some features separately. Again, needs some detection

The case you had here was a corner one: we already had done the cryptography detection, and prevented a function from running when it wasn't available, which was however always called on WEP packets.

To answer your question: yes it should have errored out, but we're trying so hard to workaround every case that it ended up being hidden
