### ISSUE TITLE
Inconsistency with timeout parameter within CAN related sockets

### ISSUE THREAD

**Issue by akorb** [secdev/scapy#2170]
**1. CAN Socket**

Native
```python
import can
from scapy.contrib.cansocket_python_can import CANSocket

python_can_socket = can.interface.Bus(bustype='socketcan', channel='vcan0', bitrate=250000)
can_socket = CANSocket(python_can_socket, timeout=5) # works
can_socket.recv() # has 5 seconds timeout now
```

Soft
```python
from scapy.contrib.cansocket_native import CANSocket

can_socket = CANSocket('vcan0', timeout=5) # error, unexpected keyword argument 'timeout'
can_socket.recv()
```

I think both or none of the constructors should support the `timeout` parameter.

**2. ISOTP Socket**
Soft
```python
def recv_with_timeout(self, timeout=1):
```

Native
Doesn't support timeout with `recv` in any way.

Maybe the `recv_with_timeout` structure could be used for the CANSockets as well.

**3. Timeout Exceptions**
Additionally, the exceptions are not consistent.

`ISOTPSoftSocket` uses
```python
raise Scapy_Exception("Timeout")
```
while
`CANSocket` (Soft) uses
```python
raise CANSocketTimeoutElapsed
```

@epozzobon 
@polybassa 
@AlexAshs

**Comment by gpotter2** [comment]
Speaking of sockets, could one of you please take care of fixing those warnings we have at the end of the tests:
```
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method ISOTPSoftSocket.__del__ of <scapy.contrib.isotp.ISOTPSoftSocket object at 0x7fe924e23d10>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method ISOTPSoftSocket.__del__ of <scapy.contrib.isotp.ISOTPSoftSocket object at 0x7fe924e231d0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method ISOTPSoftSocket.__del__ of <scapy.contrib.isotp.ISOTPSoftSocket object at 0x7fe924e56150>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method StreamSocket.__del__ of <scapy.supersocket.StreamSocket object at 0x7fe9266b8b50>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method ISOTPSoftSocket.__del__ of <scapy.contrib.isotp.ISOTPSoftSocket object at 0x7fe924e63810>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method ISOTPSoftSocket.__del__ of <scapy.contrib.isotp.ISOTPSoftSocket object at 0x7fe924e27a90>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method ISOTPSoftSocket.__del__ of <scapy.contrib.isotp.ISOTPSoftSocket object at 0x7fe924e495d0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method ISOTPSoftSocket.__del__ of <scapy.contrib.isotp.ISOTPSoftSocket object at 0x7fe924e56dd0>> ignored
```

In fact, a `SuperSocket` needs to implement a `close()` to be properly losed.

**Comment by polybassa** [comment]
@gpotter2 I created a separated issue for the mentioned problem

**Comment by polybassa** [comment]
@akorb 
**Regarding 1.** 
The underlying `python-can` library supports a `recv()` with the argument `timeout`. On the other hand, `python-can` doesn't support `select()`. This means, the function `sniff` will call the `python-can.recv()` function and blocks until this function returns. This function returns dependant on the specified `timeout` on a `python-can CANSocket`. If you are sniffing on two sockets at the same time, for example during a `bridge_and_sniff`, you want to forward packets as soon as they arrive. If sniff waits for a packet or timeout on socket1, a new packet on socket2 will be received a second later (in the worst case, timeout=1). For exactly this case, we added the optional argument `timeout` to `python-can` sockets. Native `CANSockets` support `select`, therefor a timeout is not necessary. 
The default behaviour for using a socket is to call `select` first and then `recv` if packets are available. If you instantly call `recv`, your call will block until a packet arrives.     

**2. ISOTPSocket**
We added this function, because we thought it might be useful. At the moment no one is using it, so I will remove it.
Thanks for this remark.

**3. Timeout Exceptions**
I just checked the current code of sniff, which was refactored recently. I will remove `CANSocketTimeoutElapsed`, since it is not necessary anymore. 
Thanks again for pointing me onto this.

**Comment by akorb** [comment]
Thanks. Feel free to close this issue as soon as your changes are merged.

**Comment by polybassa** [comment]
can be closed

**Comment by guedou** [comment]
Thanks!
