### ISSUE TITLE
name 'RDataField' is not defined

### ISSUE THREAD

**Issue by avildema** [secdev/scapy#2197]
OS: FreeBSD
python 2.7

   `pip install scapy==2.4.3rc4`

Steps:

python:
>\> from scapy.all import *
>\> DNSQRField
<class 'scapy.layers.dns.DNSQRField'>
>\> RDataField
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'RDataField' is not defined

this is regression, on 2.4.3rc1 works fine

**Comment by gpotter2** [comment]
We actually removed this field, which allowed us to clean up quite a bunch of DNS code :/
Did you have a specific usage for this field ?

We re-implemented it using a `MultipleTypeField`:

https://github.com/secdev/scapy/blob/4d6ea9e94cd66beb7708c57adb8241eb992a46c4/scapy/layers/dns.py#L876-L892

which for us was easier: we can re-use each subfield (IPField, IP6Field...) rather than re-implementing them all within the `RDataField`
