### ISSUE TITLE
TLSServerAutomaton cannot finish ssl handshake

### ISSUE THREAD

**Issue by acp6** [secdev/scapy#2346]
#### Brief description

Using TLSServerAutomaton (in scapy.layers.tls) to run a server, cannot finish ssl handshake with openssl s_client

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.7
-   Operating System: MacOS 10.15

#### How to reproduce

in iPython:
from scapy.all import * 
from scapy.layers.tls.automaton_srv import TLSServerAutomaton
t = TLSServerAutomaton(mycert='server-rsa-cert.pem', mykey='server-rsa-key.pem')
t.run()

in terminal:
openssl s_client -connect 127.0.0.1:4433

#### Actual result

<img width="755" alt="Screenshot 2019-11-27 10 25 06" src="https://user-images.githubusercontent.com/15442801/69688216-61ff1280-1100-11ea-8205-83cdf05e08c0.png">

I edited the file automaton_srv.py by chaning the
c = self.buffer_out[-1].msg[0].cipher
to c = self.buffer_out[-1].inner.msg[0].cipher

to resolve the AttributeError: msg, but still cannot connect to a ssl client.

**Comment by lwilms** [comment]
I had this problem as well, your error actually is because the TLSServerAutomaton does not yet support TLS1.3 and openssl uses TLS1.3 as a standard to communicate with a TLS Server.

try: openssl s_client -tls1_2 -connect 127.0.0.1:4433

That said, I have a different error message, which might give an author a motivation.
I had the same code, but a Python version 3.6.

[log.txt](https://github.com/secdev/scapy/files/4370397/log.txt)

**Comment by gpotter2** [comment]
Sorry for the delay.

Please note we're very actively working on bringing TLS 1.3 capabilities. You can track the progress on https://github.com/secdev/scapy/pull/2132

Most of the bugs mentioned should be fixed by now. The implementation isn't finished (still GREASE to handle for instance..).

**Comment by gpotter2** [comment]
Fixed. see https://github.com/secdev/scapy/pull/2132
