### ISSUE TITLE
Command Injection in scapy.all.PcapReader()

### ISSUE THREAD

**Issue by MrBr4ckets** [secdev/scapy#2597]
#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.7.7`
-   Operating System: `Kali 5.4.0-kali4-amd64`

#### How to reproduce

PoC File : 

```
import scapy.all
import sys

inject_attack = sys.argv[1]
with scapy.all.PcapReader(inject_attack) as pr:
	print(pr.read_all())
```
Execution : python3 PoC.py `whoami` (with back quote the command)

Output:

![imagen](https://user-images.githubusercontent.com/17044832/79672957-37dbe900-81a4-11ea-95b7-f0181c47aa87.png)

In error FileNotFoundError we can see the out from command.

**Comment by polybassa** [comment]
Thank you very much for this report.

I might be wrong, but from the information you provided, I doubt that a command was injected into the PcapReader function. 

From what I see in your picture, the call to whoami is executed in your shell, and the output is provided as argument to scapy. So the command execution already happened before the python program is started.

You can see the output of whoami, because the PcapReader tried to open a file with a name identical to the output of whoami.

Can you verify this?

**Comment by MrBr4ckets** [comment]
I think that if it is injected into python because I don't have any file with the name of whoami or its output, so the backticks do the execution inside the program and in its defect it would affect the function PcapReader ()

Files in folder: 
![imagen](https://user-images.githubusercontent.com/17044832/79674107-27307080-81ae-11ea-9d12-a9953c0a8898.png)

(whoami contain backticks )

**Comment by gpotter2** [comment]
That's just how bash works. What's the issue
```
$ echo `whoami`
gpotter
```
