### ISSUE TITLE
`send` sends out multiple Dot11Auth packets

### ISSUE THREAD

**Issue by fe64970103** [secdev/scapy#2638]
I'm using the latest scapy versin from:
`pip install --upgrade git+git://github.com/secdev/scapy`

**#### Brief description**
When using send function to send out the Dot11Auth packet scapy sends out multiple packets. The amount of duplicates varies, currently in my setup 5. This is confirmed by using an external wireless capturing tool.

**#### Environment**

-   Scapy version: `5837c08d6b6c969eea7784e7f3981b0c49f03601`
-   Python 3.8.1
-   Linux/OpenWRT

**#### How to reproduce**

packet = Dot11(addr1 = self.bssid , addr2 = self.client, addr3 = self.bssid) / Dot11Auth(algo=0, seqnum=0x0001, status=0x0000)
send(packet, iface = self.iface, count = 1, verbose = False, realtime = True)

**Comment by gpotter2** [comment]
This is a more-less known bug. 
Scapy builds the raw packet then just send it to the OS using a raw socket. We do not send the packet multiple times, but it is likely that the OS or the driver picks it and acts weirdly about it. It's likely because we inject unknown payloads without really asking the OS first.

There is very likely nothing we can do about that :/
