### ISSUE TITLE
Raw ICMP requests only sometimes get their answers

### ISSUE THREAD

**Issue by moshesakajo** [secdev/scapy#2675]
#### Brief description
The following script lines generate a raw ICMP request.
The problem is that most of the time the ICMP replies are not identified
by **sr1**. I have even tried to increase the TO and that didn't help

```
from scapy.all import sr1, IP, ICMP

pkt = IP(dst=device_ip) / ICMP()

sr1(pkt, timeout=2, verbose=True)
```

#### Environment

-   Scapy version: `scapy version 2.4.3.dev681`
-   Python version: `3.8.3`
-   Operating System: `Windows 10`
-   Npcap version: `0.9991`

The device which I send the ICMP requests to is on the same subnet as the host which I run the script from. This device replies to each of the ICMP requests (verified with Wireshark). pinging this device will result in 100% success.
When I used scapy version 2.4.3 I succeeded less in getting ICMP replies. The scapy dev release is better but still I cannot rely on it.
I can tell that scapy version 2.4.3 on a Windows 7 with Winpcap and Python version 3.5.2 was 100% reliable

#### How to reproduce

Send multiple ICMP requests to a valid and reachable host

#### Actual result

most of the ICMP replies are not identified

#### Expected result

All the ICMP requests should have ICMP replies

**Comment by gpotter2** [comment]
If you're on very high traffic, it could be that scapy misses the answers. You can use a BPF filter: `sr(..., filter="icmp")` to improve the sniffing performances.

Otherwise this sounds more like an issue related to your sniffing conditions than scapy. Feel free to turn on `conf.debug_match` and check the packets in `conf.debug.recv`: if you can find the answer there that is not detected by scapy, then it's bug. otherwise, likely not.
