### ISSUE TITLE
IPSec Authentication Header appears to be broken

### ISSUE THREAD

**Issue by kikones34** [secdev/scapy#2697]
#### Brief description

The Authentication Header (AH) class does not seem to properly update its fields like other type of packets do, and generates malformed packets.
Happens both when used in conjunction wtih IPv4 and IPv6, with any upper layer protocol.

#### Environment

-   Scapy version: `2.4.3.dev699`
-   Python version: `3.8.3`
-   Operating System: `Kali Linux 2020.2`

#### How to reproduce

Attempt to craft a full packet with an Authentication Header, for example, using IPv6 and a ping request:

``` python
p = IPv6() / AH(icv=b'abcd') / ICMPv6EchoRequest()
```

#### Actual result

The `nh` and `payloadlen` fields of the header are not updated automatically, creating a malformed packet.

``` python
> p = IPv6() / AH(icv=b'abcd') / ICMPv6EchoRequest()
> p.show2()
###[ IPv6 ]### 
  version   = 6
  tc        = 0
  fl        = 0
  plen      = 24
  nh        = AH Header
  hlim      = 64
  src       = ::1
  dst       = ::1
###[ AH ]### 
     nh        = hopopt
     payloadlen= 0
     reserved  = 0
     spi       = 0x0
     seq       = 0
     icv       = 61626364
     padding   = b''
###[ IP ]### 
        version   = 0
        ihl       = 0
        tos       = 0x0
        len       = 0
        id        = 1
        flags     = 
        frag      = 0
        ttl       = 64
        proto     = hopopt
        chksum    = None
        src       = 127.0.0.1
        dst       = 127.0.0.1
        \options   \
```

When manually setting the `nh` and `payloadlen` fields to the correct value, the produced packet is correct when inspected in Wireshark, however, the `show2` function displays it wrongly:

``` python
> p = IPv6() / AH(nh=58, payloadlen=2, icv=b'abcd') / ICMPv6EchoRequest()
> p.show2()
###[ IPv6 ]### 
  version   = 6
  tc        = 0
  fl        = 0
  plen      = 24
  nh        = AH Header
  hlim      = 64
  src       = ::1
  dst       = ::1
###[ AH ]### 
     nh        = ipv6_icmp
     payloadlen= 2
     reserved  = 0
     spi       = 0x0
     seq       = 0
     icv       = 61626364
     padding   = b''
###[ Raw ]### 
        load      = '\x80\x00\x7f\xbb\x00\x00\x00\x00'
```

![image](https://user-images.githubusercontent.com/4391024/86147756-11b6bb80-bafa-11ea-9ddf-1d9745876448.png)

#### Expected result

The AH should function correctly when combined with other headers. The `nh` field should be automatically updated to the corresponding type. The `payloadlen` field should be updated according to the length of the `icv` field. Padding should also be automatically added when `icv` is not a multiple of 32-bit.

**Comment by g-mahieux** [comment]
Hi,

I believe you have the wrong use model for IPsec with Scapy. What you're doing is manually building a packet, layer-by-layer. Although it's usually how it's done with Scapy, it does not work like that for IPsec (and MACsec similarly).

Principle is to build your packet, then apply IPsec processing on it before sending. IPsec processing is done by first creating a Security Association object which basically holds the state of your secure connection (cryptographic algorithm, key, sequence number, ..), and then using it on the packet.

Quick example:
```
# Define a Security Association for IPsec processing
sa = SecurityAssociation(AH, spi=0x222, auth_algo='SHA2-384-192', auth_key=b'secret key')

# Create packet
p = IPv6() / ICMPv6EchoRequest()
p.show2()

# Send: IPsec encapsulation
e = sa.encrypt(p)
e.show2()

# Receive: IPsec decapsulation
d = sa.decrypt(e)
d.show2()

# Check received packet is identical to original
assert raw(d) == raw(p)
```
Gives you;
```
###[ IPv6 ]###
  version   = 6
  tc        = 0
  fl        = 0
  plen      = 8
  nh        = ICMPv6
  hlim      = 64
  src       = ::1
  dst       = ::1
###[ ICMPv6 Echo Request ]###
     type      = Echo Request
     code      = 0
     cksum     = 0x7fbb
     id        = 0x0
     seq       = 0x0
     data      = ''

###[ IPv6 ]###
  version   = 6
  tc        = 0
  fl        = 0
  plen      = 48
  nh        = AH Header
  hlim      = 64
  src       = ::1
  dst       = ::1
###[ AH ]###
     nh        = ipv6_icmp
     payloadlen= 8
     reserved  = 0
     spi       = 0x222
     seq       = 1
     icv       = 466dcf17203e1f278a423333c4ed0230948515bfb4a4449e00000000
     padding   = ''
###[ Raw ]###
        load      = '\x80\x00\x7f\xbb\x00\x00\x00\x00'

###[ IPv6 ]###
  version   = 6
  tc        = 0
  fl        = 0
  plen      = 8
  nh        = ICMPv6
  hlim      = 64
  src       = ::1
  dst       = ::1
###[ ICMPv6 Echo Request ]###
     type      = Echo Request
     code      = 0
     cksum     = 0x7fbb
     id        = 0x0
     seq       = 0x0
     data      = ''
```

I invite you to take a look at the [unit test file for IPsec](https://github.com/secdev/scapy/blob/master/test/ipsec.uts) which will show you more usage examples.

Like you're doing it now, AH can't be correct because there's no way for Scapy to set values appropriately without a SecurityAssociation object for context. For instance, even payloadlen could depend on padding/alignement requirement of the particular algorithm in use.

As for why show2() shows the ICMPv6EchoRequest as "raw":
If you check [ipsec.py](https://github.com/secdev/scapy/blob/master/scapy/layers/ipsec.py), class SecurityAssociation, method _encrypt_ah(), you see that the returned packet is the product of the sign() method of the selection cryptographic algorithm, and that is definitely going to return an array of bytes and not a Packet object.
In the case of ESP, you'd get encrypted gibberish so you're stuck with raw bytes. For AH you could probably recast those bytes into a Packet object, but you'd break the symmetry of implementation between ESP and AH, which is probably a good enough reason not to do it.

Hope that helps!

**Comment by guedou** [comment]
@g-mahieux thanks for your answer.

**Comment by kikones34** [comment]
> Hi,
> 
> I believe you have the wrong use model for Scapy's IPsec implementation. What you're doing is manually building a packet, layer-by-layer. Although it's usually how one works with Scapy, it does not work like that for IPsec (and MACsec similarly).
> 
> The principle is to build your packet leaving out IPsec, then apply IPsec processing on that packet. IPsec processing is done by first creating a Security Association object which basically holds the state of your secure connection (cryptographic algorithm, key, sequence number, ..), and then using it on the packet.
> 
> Quick example:
> 
> ```
> # Define a Security Association for IPsec processing
> sa = SecurityAssociation(AH, spi=0x222, auth_algo='SHA2-384-192', auth_key=b'secret key')
> 
> # Create packet
> p = IPv6() / ICMPv6EchoRequest()
> p.show2()
> 
> # Send: IPsec encapsulation
> e = sa.encrypt(p)
> e.show2()
> 
> # Receive: IPsec decapsulation
> d = sa.decrypt(e)
> d.show2()
> 
> # Check received packet is identical to original
> assert raw(d) == raw(p)
> ```
> 
> Gives you;
> 
> ```
> ###[ IPv6 ]###
>   version   = 6
>   tc        = 0
>   fl        = 0
>   plen      = 8
>   nh        = ICMPv6
>   hlim      = 64
>   src       = ::1
>   dst       = ::1
> ###[ ICMPv6 Echo Request ]###
>      type      = Echo Request
>      code      = 0
>      cksum     = 0x7fbb
>      id        = 0x0
>      seq       = 0x0
>      data      = ''
> 
> ###[ IPv6 ]###
>   version   = 6
>   tc        = 0
>   fl        = 0
>   plen      = 48
>   nh        = AH Header
>   hlim      = 64
>   src       = ::1
>   dst       = ::1
> ###[ AH ]###
>      nh        = ipv6_icmp
>      payloadlen= 8
>      reserved  = 0
>      spi       = 0x222
>      seq       = 1
>      icv       = 466dcf17203e1f278a423333c4ed0230948515bfb4a4449e00000000
>      padding   = ''
> ###[ Raw ]###
>         load      = '\x80\x00\x7f\xbb\x00\x00\x00\x00'
> 
> ###[ IPv6 ]###
>   version   = 6
>   tc        = 0
>   fl        = 0
>   plen      = 8
>   nh        = ICMPv6
>   hlim      = 64
>   src       = ::1
>   dst       = ::1
> ###[ ICMPv6 Echo Request ]###
>      type      = Echo Request
>      code      = 0
>      cksum     = 0x7fbb
>      id        = 0x0
>      seq       = 0x0
>      data      = ''
> ```
> 
> I invite you to take a look at the [IPsec unit tests](https://github.com/secdev/scapy/blob/master/test/ipsec.uts) which will show you more usage examples.
> 
> Like you're doing it now, AH can't be correct because there's no way for Scapy to set values appropriately without a Security Association object for context. For instance, even payloadlen could depend on padding/alignement requirement of the particular algorithm in use.
> 
> As for why show2() shows the encapsulated ICMPv6EchoRequest as "raw" (at least in my example):
> If you check [ipsec.py](https://github.com/secdev/scapy/blob/master/scapy/layers/ipsec.py), class SecurityAssociation, method _encrypt_ah(), you see that the returned packet is the product of the sign() method of the selected cryptographic algorithm, and that is definitely going to return an array of bytes and not a Packet object.
> In the case of ESP, you'd get encrypted gibberish so you're stuck with raw bytes. For AH you could probably recast those bytes into a Packet object, but you'd break the symmetry of implementation between ESP and AH, which is probably a good enough reason not to do it.
> 
> Hope that helps!

Thank you for the detailed answer!
For my use case (IPv6 header fuzzing) I really did need to manually build all layers to e.g. put the authentication header in an unexpected place, so I just ended up just setting every field manually. After your explanation, however, I see that the current implementation makes a lot of sense, and I don't think it needs to be changed. Closing the issue.

**Comment by MuhammadBor** [comment]
> Hi,
> 
> I believe you have the wrong use model for Scapy's IPsec implementation. What you're doing is manually building a packet, layer-by-layer. Although it's usually how one works with Scapy, it does not work like that for IPsec (and MACsec similarly).
> 
> The principle is to build your packet leaving out IPsec, then apply IPsec processing on that packet. IPsec processing is done by first creating a Security Association object which basically holds the state of your secure connection (cryptographic algorithm, key, sequence number, ..), and then using it on the packet.
> 
> Quick example:
> 
> ```
> # Define a Security Association for IPsec processing
> sa = SecurityAssociation(AH, spi=0x222, auth_algo='SHA2-384-192', auth_key=b'secret key')
> 
> # Create packet
> p = IPv6() / ICMPv6EchoRequest()
> p.show2()
> 
> # Send: IPsec encapsulation
> e = sa.encrypt(p)
> e.show2()
> 
> # Receive: IPsec decapsulation
> d = sa.decrypt(e)
> d.show2()
> 
> # Check received packet is identical to original
> assert raw(d) == raw(p)
> ```
> 
> Gives you;
> 
> ```
> ###[ IPv6 ]###
>   version   = 6
>   tc        = 0
>   fl        = 0
>   plen      = 8
>   nh        = ICMPv6
>   hlim      = 64
>   src       = ::1
>   dst       = ::1
> ###[ ICMPv6 Echo Request ]###
>      type      = Echo Request
>      code      = 0
>      cksum     = 0x7fbb
>      id        = 0x0
>      seq       = 0x0
>      data      = ''
> 
> ###[ IPv6 ]###
>   version   = 6
>   tc        = 0
>   fl        = 0
>   plen      = 48
>   nh        = AH Header
>   hlim      = 64
>   src       = ::1
>   dst       = ::1
> ###[ AH ]###
>      nh        = ipv6_icmp
>      payloadlen= 8
>      reserved  = 0
>      spi       = 0x222
>      seq       = 1
>      icv       = 466dcf17203e1f278a423333c4ed0230948515bfb4a4449e00000000
>      padding   = ''
> ###[ Raw ]###
>         load      = '\x80\x00\x7f\xbb\x00\x00\x00\x00'
> 
> ###[ IPv6 ]###
>   version   = 6
>   tc        = 0
>   fl        = 0
>   plen      = 8
>   nh        = ICMPv6
>   hlim      = 64
>   src       = ::1
>   dst       = ::1
> ###[ ICMPv6 Echo Request ]###
>      type      = Echo Request
>      code      = 0
>      cksum     = 0x7fbb
>      id        = 0x0
>      seq       = 0x0
>      data      = ''
> ```
> 
> I invite you to take a look at the [IPsec unit tests](https://github.com/secdev/scapy/blob/master/test/ipsec.uts) which will show you more usage examples.
> 
> Like you're doing it now, AH can't be correct because there's no way for Scapy to set values appropriately without a Security Association object for context. For instance, even payloadlen could depend on padding/alignement requirement of the particular algorithm in use.
> 
> As for why show2() shows the encapsulated ICMPv6EchoRequest as "raw" (at least in my example): If you check [ipsec.py](https://github.com/secdev/scapy/blob/master/scapy/layers/ipsec.py), class SecurityAssociation, method _encrypt_ah(), you see that the returned packet is the product of the sign() method of the selected cryptographic algorithm, and that is definitely going to return an array of bytes and not a Packet object. In the case of ESP, you'd get encrypted gibberish so you're stuck with raw bytes. For AH you could probably recast those bytes into a Packet object, but you'd break the symmetry of implementation between ESP and AH, which is probably a good enough reason not to do it.
> 
> Hope that helps!

Hello,

Thank you for your detailed explanation on the correct usage of Scapy for IPsec processing. You're absolutely right about the approach of creating a Security Association and applying it to the packet, rather than manually crafting each layer when dealing with IPsec.

Regarding the issue you've highlighted with AH tunnel or transport mode, and the identification of the protocol when monitoring with tools like Wireshark, it indeed presents a subtle challenge. When packets are sent through interfaces with AH encapsulation, Wireshark or similar tools might not always correctly parse and display the AH headers, instead showing the inner packet directly. This misrepresentation is typically due to the way these monitoring tools interpret the packet layers, particularly when encryption or certain forms of encapsulation are involved? As far as I recollect, saving your example packet generation as pcap and open it in Wireshark shows an ICMP req.

This small hiccup can sometimes complicate debugging and traffic analysis. However, ensuring that all packet layers are correctly formed as per the IPsec standards, and checking configurations can mitigate some of these observational inconsistencies. Is there any workaround?
