### ISSUE TITLE
Craft packages for stress

### ISSUE THREAD

**Issue by alexrebell** [secdev/scapy#2738]
Hello, comrades.
Please tell us what options are available for creating packages that will serve as testing for this test. I need to check my router, which is connected by wire and Wi-Fi. I need to send such packets to load my router to the failure state. Please share your knowledge.
Thank you very much.

**Comment by polybassa** [comment]
Hello comrade,

I'm happy that you like Scapy, but this is not a forum. You can ask your question on gitter or check the documentation https://scapy.readthedocs.io/en/latest/.
Also the unit test of certain layers provide good examples.

Please close this thread, since it's not an issue to the main project.

**Comment by alexrebell** [comment]
thank you, but I can't find any information for myself
