### ISSUE TITLE
SOMEIP message seems to improperly set MethodId

### ISSUE THREAD

**Issue by kjczarne** [secdev/scapy#2807]
#### Brief description

SOMEIP message seems to improperly set MethodId.

#### Environment

-   Scapy version: both 2.4.3 and 2.4.4
-   Python version: 3.7.6
-   Operating System: Windows 10

#### How to reproduce

Run the following:
```python
import binascii as bs
import time

sip = SOMEIP()
ids = [0x3000, 0x4000, 0x5000, 0x6000, 0x7000, 0x8000, 0x9000, 0xa000]

for i in ids:
    sip.method_id = i
    print(bs.hexlify(bytes(sip)))
```
You will see that after reaching 0x7000 the value wraps around. Not sure if this is intentional or not but AUTOSAR spec states the following: 

> Service Discovery messages shall use the Method-ID (16
> Bits) of 0x8100.

Hence setting values above 0x8000 should be an option.

#### Actual result

Here's the printed output from the above script:
```
b'00003000000000080000000001010000'
b'00004000000000080000000001010000'
b'00005000000000080000000001010000'
b'00006000000000080000000001010000'
b'00007000000000080000000001010000'
b'00000000000000080000000001010000'
b'00001000000000080000000001010000'
b'00002000000000080000000001010000'
```

#### Expected result

```
b'00003000000000080000000001010000'
b'00004000000000080000000001010000'
b'00005000000000080000000001010000'
b'00006000000000080000000001010000'
b'00007000000000080000000001010000'
b'00008000000000080000000001010000'
b'00009000000000080000000001010000'
b'0000a000000000080000000001010000'
```

#### Related resources

Not applicable.

**Comment by polybassa** [comment]
Hi, we followed this specification. Which one do you use?


Nils

**Comment by polybassa** [comment]
6.2.3.2.1 Structure of the Message ID
[TR_SOMEIP_00036] d An event shall be part of zero to many eventgroups and an
eventgroup shall contain zero to many events. A field shall be part of zero to many
eventgroups and an eventgroup can contain zero to many fields. c()
[TR_SOMEIP_00037] d Currently empty eventgroups are not used and events as well
as fields are mapped to at least one eventgroup. c()
[TR_SOMEIP_00038] d For RPC calls we structure the ID in 2
16 services with 2
15 meth-
ods:
Service ID [16 Bit] 0 [1 Bit] Method ID [last 15 Bit]
c()
[TR_SOMEIP_00039] d With 16 Bit Service-ID and a 16 Bit Method-ID starting with a
0-Bit, this allows for up to 65536 services with up to 32768 methods each. c()
[TR_SOMEIP_00040] d Since events and notifications (see Notification or Publish/Sub-
scribe) are transported using RPC, the ID space for the events is further structured:
Service ID [16 Bit] 1 [1 Bit] Event ID [last 15 Bit]
c()
[TR_SOMEIP_00041] d This means that up to 32768 events or notifications per service
are possible. c
--

**Comment by kjczarne** [comment]
Hi Nils! I've just realized SOME/IP Service Discovery follows a separate spec. 
https://www.autosar.org/fileadmin/user_upload/standards/foundation/1-2/AUTOSAR_PRS_SOMEIPServiceDiscoveryProtocol.pdf
The above is the one I was referring to in my question. So it's not a bug but I guess a feature request...? 🙏😌

**Comment by polybassa** [comment]
Hi, @kjczarne unfortunately I wasn't the author of this protocol implementation, but what I see from the implementation is, that "method_ids" >= 0x8000 are called "event_ids" in our current implementation. This is also used in the bind of Service Discovery packets: https://github.com/secdev/scapy/blob/1ca4925099f9e4052f71b4f26af254652d42e66b/scapy/contrib/automotive/someip.py#L513-L516 

If the specifications are not clear here, we have to decide to follow one.

From my understanding, the current implementation is not wrong. If we have a defined way to distinguished between "method_id" and "event_id", we can implement a condition for that. Do you see a condition where it would make sense to change the field description from `method_id / event_id ([0x0 - 0x7fff / 0x8000 - 0xffff])` to `method_id ([0x0 - 0xffff])`?

**Comment by kjczarne** [comment]
Thanks for assistance @polybassa ! I must have missed the `event_id` field somehow. I've checked once again and yes, the implementation seems to be correct. If I find any other potential issues regarding SOME/IP I'll keep you posted. 😉

For anyone struggling with a similar issue in the future, make also sure you're using a complete layer stack, i.e. `msg = SOMEIP() / SD()` and then `msg.event_id = 0x8100` will work but if you have a `msg = SOMEIP()` and try to set `event_id`, this won't work as there will be missing context.

**Comment by polybassa** [comment]
Thanks for your help.
