### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by mahmad2504** [secdev/scapy#3031]
Scapy is under GPL but https://github.com/secdev/scapy/blob/master/doc/scapy/index.rst mentions that "This document is under a Creative Commons Attribution - Non-Commercial - Share Alike 2.5 license"  
Does that means i cannot use scapy in my commercial product?

**Comment by guedou** [comment]
Scapy is released under GPLv2. You must comply with this license when using it.

**Comment by charles2910** [comment]
Hi, I'm reopening this issue because there are a couple files under `doc/scapy` and a commit that states the license as CC-By-NC-SA-2.5. As [pointed out in the comment](https://github.com/secdev/scapy/issues/3321#issuecomment-1398738672) in #3321, it makes these files unsuitable for Debian. I'll paste the snippets of the files for the record.

`doc/scapy/index.rst`:

```rst
.. Scapy documentation master file, created by sphinx-quickstart on Mon Sep  8 19:37:39 2008.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.
 
Welcome to Scapy's documentation!
=================================
 
.. image:: graphics/scapy_logo.png
   :scale: 20
   :align: center
 
:Version: |version|
:Release: |release|
:Date: |today|
 
This document is under a `Creative Commons Attribution - Non-Commercial 
- Share Alike 2.5 <http://creativecommons.org/licenses/by-nc-sa/2.5/>`_ license.
```

`doc/scapy/layers/automotive.rst`:

```rst
.. note:: This document is under a `Creative Commons Attribution - Non-Commercial - Share Alike 2.5 <http://creativecommons.org/licenses/by-nc-sa/2.5/>`_ license.

#################################
Automotive-specific Documentation
#################################

.. sectionauthor:: Nils Weiss <nils@we155.de>
```

And the commit mentioning the license is 652baabe1fffc3dff6c3f11d37763e529ee3cb8f. Which says:

> Added several tutorial sections, one-liners and recipes by Peter Kacherginsky
>
> Peter had written a very nice tutorial on his web site
> http://thesprawl.org/memdump/doku.php?id=tools:scapy
> and kindly allowed me to add it to our docs under the
> CC BY-NC-SA-2.5 license.

Things are a little gray since most of the docs files don't have a license boilerplate, but looking the online documentation landing page it seems to imply everything is under CC-By-NC-SA-2.5 in my opinion (I'm not an lawyer or expert on the matter though):

![image](https://user-images.githubusercontent.com/34252251/214704356-af638d97-0b5e-4317-8c34-4223d4b9e670.png)
