### ISSUE TITLE
How correctly define ISO7816 APDU layer

### ISSUE THREAD

**Issue by abioteau** [secdev/scapy#3194]
#### Brief description

I'm newby on scapy and I want to define ISO7816 APDU layer. 

#### Environment

-   Scapy version: `2.4.4`
-   Python version: `3.6`
-   Operating System: `Windows 10`

#### Actual result

I have define APDU Header as below but I do not know how define others optionals fields "Lc", "Data" and "Le" and "Data" field could be a "payload" from another layer.

`
class APDUHeader(Packet):
    fields_desc = [
        XByteField("CLA", 0),
        XByteField("INS", 0),
        XByteField("P1", 0),
        XByteField("P2", 0)
    ]

class APDUStatus(Packet):
    fields_desc = [
        XByteField("SW1", 0),
        XByteField("SW2", 0)
    ]
`

#### Expected result

I want to forge APDU command and dissect APDU response.

#### Related resources

Standard : ISO/IEC 7816-4
Public link : https://en.wikipedia.org/wiki/Smart_card_application_protocol_data_unit

**Comment by polybassa** [comment]
Hi, 
nice idea to add ISO7816 to Scapy.
IMHO, the easiest way to define ``Lc``, ``Data`` and ``Le`` would be in individual packets, that you can append to an ``APDUHeader``. Example: ```APDUHeader(CLA=2, INS=42, ...) / SIMCommand(whatever=42)```

Parsing the response might be a little bit difficult, since you need to insert a data field with a variable length based on the request. 

I had a similar problem during the implementation of CCP. Basically the response class could only be determined from the request, which would also be the case here. I've used the answers function to determine the correct class. The advantage was, that the answers function has access to the request and the response.  https://github.com/secdev/scapy/blob/11832deee0067e1db2660ff1f61e5d4e979adf27/scapy/contrib/automotive/ccp.py#L564-L586

AFAIK ISO7816, you will always have a request-response like communication without any other packet in the middle, so determining the response class only based on the request would be doable here.

**Comment by abioteau** [comment]
@polybassa thanks for your advise.

**Comment by guedou** [comment]
Closing this issue as the answer seems complete.
