### ISSUE TITLE
Add SPDX License identifier

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#3321]
We should use https://spdx.dev/ids/ to easily identify GPLv2 in Scapy source code.

That is a good opportunity to change the license of MPL licensed files.

**Comment by polybassa** [comment]
How should the file header in Scapy source files look like?
```
# This file is part of Scapy
# See https://scapy.net/ for more information
# Copyright (C) Some One <someone@home.tdl>
# SPDX-License-Identifier: GPL-2.0-only
```

**Comment by zabbal** [comment]
Just the last line will do, although personally I would prefer 
`# SPDX-License-Identifier: GPL-2.0-or-later`

**Comment by guedou** [comment]
@zabbal Scapy is licensed under GPL 2.0 only.

@polybassa I would prefer this
```
# SPDX-License-Identifier: GPL-2.0-only
# This file is part of Scapy
# See https://scapy.net/ for more information
# Copyright (C) Some One <someone@home.tdl>
```

I wish we could remove the Copyrights comments, but this is another topic =)

**Comment by polybassa** [comment]
What would you prefer, instead?

On December 21, 2021 9:21:22 AM GMT+01:00, Guillaume Valadon ***@***.***> wrote:
***@***.*** Scapy is licensed under GPL 2.0 only.
>
***@***.*** I would prefer this

**Comment by guedou** [comment]
I don't understand your question =\

**Comment by polybassa** [comment]
You said, you wish to remove the copyright comments. So I was wondering how you would state the copyright instead.
-- 
Viele Grüße

Nils Weiß

**Comment by guedou** [comment]
We cannot remove the copyrights without asking the authors individually. That’s a tremendous task independent of adding the SPDX identifier

**Comment by gpotter2** [comment]
What would be the format if existing files provide the year?
e.g.
```
# This file is part of Scapy
# Copyright (C) 2007, 2008, 2009 Arnaud Ebalard
#               2015, 2016, 2017 Maxence Tury
# This program is published under a GPLv2 license
```

**Comment by charles2910** [comment]
Hi, guys. You've added the spdx identifier in all the source code but you missed the documentation. I think it would be very important to have it there too.

As far as I understand, the `doc/scapy/*` is licensed as Creative Commons Attribution Non Commercial Share Alike 2.5 Generic. Is this correct?

Obs: I've come accross this while packaging it for Debian and I'll need to drop the documentation because of the license. The Debian Free Software Guidelines (DFSG) mandates the following:

> 6. No Discrimination Against Fields of Endeavor
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

So the Non Commercial breaks it and makes it unfit to be in the Debian's archive.
