### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by KSGJ-CLOUD** [secdev/scapy#3481]
I used sniff () to grab the interface package, but this problem occurred ‘PermissionError: [Errno 1] Operation not permitted’.I don't know why.

**Comment by guedou** [comment]
Please do not harass us. This is bas behavior! Use gitter to ask your question.

**Comment by polybassa** [comment]
Or have a look at closed issues: https://github.com/secdev/scapy/issues?q=is%3Aissue+permission

**Comment by KSGJ-CLOUD** [comment]
> 

I must make three points clear. I am not harassing you. I am just explaining the facts and the problems I encounter. I hope you can help, not harass you as you understand.
First of all, I really encountered this problem. Next, I will put a picture to prove it
Secondly, I'm giving you feedback. I hope you can help
Finally, every time I send a question, you don't say to solve it, but forcibly close it and don't give a positive answer.
![image](https://user-images.githubusercontent.com/71766358/145167005-727e392b-ca18-42f5-b024-5a9146135c53.png)

**Comment by polybassa** [comment]
Please understand that this is an issue tracker of issues IN scapy. Permission errors are usually caused by your operating system. 

We have no way to fix those in scapy. Therefore this is a usage question and not an issue in the code base. So please use Gitter to get further help and please understand that the objective of the maintainer is to keep the issue tracker clean. Otherwise maintaining gets harder and real issues get lost.
