### ISSUE TITLE
Non-commercial licensing in volatile.py?

### ISSUE THREAD

**Issue by hyandell** [secdev/scapy#3823]
### Brief description

Hi Scapy folk,

I noticed that PR #3508 introduced code that was 'inspired by' a non-commercial licensed project ( https://github.com/longld/peda ). 

Digging into the peda code, it looks like the matching code is:

    https://github.com/longld/peda/blob/master/lib/utils.py#L565

This seems like a concern given your project licensing isn't non-commercial.

### Scapy version

2.5.0rc3

### Python version

-

### Operating system

-

### How to reproduce

Visual inspection of the two pieces of code.

**Comment by polybassa** [comment]
Hi Henri,

Thank you very much for this report.

To my understanding, all points of CC-BY-SA-NC-3 except the NC part should not make any problems in the current way the code is used, since attribution is giving to the author.

Regarding NC, I'm not a lawyer. Since gplv2 code is by definition free to everyone, I don't see a commercial use by the Scapy project of the relevant CC licensed code. Even if you use scapy in a product, you are forced to give a copy of your code for free, which makes commercial licensing impossible anyway.

So I don't see an issue with CC licensed code here. 

Could you please share your understanding of the license compatibility?

Thanks!
-- 
Viele Grüße

Nils Weiß

**Comment by gpotter2** [comment]
@polybassa You can't include Non-Commercial code in code that can be used comercially like GPLv2.

**Comment by polydroi** [comment]
Alright, thanks for clarification.

**Comment by gpotter2** [comment]
Thanks for the notice @hyandell. This should be fixed in https://github.com/secdev/scapy/pull/3824
