### ISSUE TITLE
packet.haslayer(DNS) not filtering the packets having DNS layer same as in issue#548

### ISSUE THREAD

**Issue by syed-amar-zaidi** [secdev/scapy#3865]
### Brief description

As i mentioned it is same as it was in issue# 548 when i filter the packets with
`if  packet.haslayer(UDP):
     packet.show()
`
it shows it has layer DNS but filtering with just haslayer(DNS) does not working.

### Scapy version

2.4.4

### Python version

3.9.2

### Operating system

Kernel Linux 6.0.0-2parrot1-amd64 x86_64

### How to reproduce

writing a python script filter the packets using `packet.haslayer(UDP)` it show the packet has layer DNS but when filtering with `packet.haslayer(DNS)` does not work

**Comment by mspncp** [comment]
@syed-amar-zaidi the issue you are referring to has the number #568, not 548. That issue was closed because the author only provided vague explanations and was not able to provide evidence that there is actually a bug in Scapy and not in his script.

My guess is that in your case the problem is also caused by an error in your script, not by Scapy. So if you show us your script then we might be able to locate the error. Stating only personal interpretations like "is not working" or "same as issue x" is not really helpful for analysis.

If it is really a Scapy bug (which I doubt), then it should be straight forward for you to prove it with a short reproducer script. You don't need to provide a network capture (tcpdump/Wireshark) as reproducer or something similar sophisticated. Just "save" the offending packet as a raw byte string using `data = raw(pkt)`  and then send us a short Python snippet which exhibits the wrong behaviour and explain to us why you think that Scapy is behaving incorrectly.

```python

data = b'...<raw packet data>...0'

pkt=Ether(data)

...<your code here>...
```
