### ISSUE TITLE
Failed to build docs

### ISSUE THREAD

**Issue by marek22k** [secdev/scapy#4215]
### Brief description

Hello,

I would like to build the documentation for offline purposes myself. Since there was no documentation for this, I assumed that the Makefile can be used, but this does not work.

### Scapy version

2.5.0

### Python version

Python 3.12.0

### Operating system

Debian Linux 6.5.0-0.deb12.4-amd64

### How to reproduce

```
$ git clone https://github.com/secdev/scapy.git
$ cd scapy/doc/scapy/
$ make singlehtml
$ make latexpdf
```

### Actual result

```
$ make singlehtml
Running Sphinx v7.2.6
making output directory... done

Extension error (scapy_doc):
Handler <function builder_inited_handler at 0x7f8f97cd7380> for event 'builder-inited' threw an exception (exception: [Errno 2] No such file or directory: 'tox')
make: *** [Makefile:20: singlehtml] Error 2
$ make latexpdf
Running Sphinx v7.2.6
making output directory... done

Extension error (scapy_doc):
Handler <function builder_inited_handler at 0x7f7f61a03380> for event 'builder-inited' threw an exception (exception: [Errno 2] No such file or directory: 'tox')
make: *** [Makefile:20: latexpdf] Error 1
```

### Expected result

A PDF or HTML file.

**Comment by guedou** [comment]
Thanks for your interest in Scapy. Using ‘toc -e docs’ will do the job.Sent from my iPhoneOn 26 Dec 2023, at 15:43, Marek Küthe ***@***.***> wrote:﻿
Brief description
Hello,
I would like to build the documentation for offline purposes myself. Since there was no documentation for this, I assumed that the Makefile can be used, but this does not work.
Scapy version
2.5.0
Python version
Python 3.12.0
Operating system
Debian Linux 6.5.0-0.deb12.4-amd64
Additional environment information
No response
How to reproduce
$ git clone https://github.com/secdev/scapy.git
$ cd scapy/doc/scapy/
$ make singlehtml
$ make latexpdf

Actual result
$ make singlehtml
Running Sphinx v7.2.6
making output directory... done

Extension error (scapy_doc):
Handler <function builder_inited_handler at 0x7f8f97cd7380> for event 'builder-inited' threw an exception (exception: [Errno 2] No such file or directory: 'tox')
make: *** [Makefile:20: singlehtml] Error 2
$ make latexpdf
Running Sphinx v7.2.6
making output directory... done

Extension error (scapy_doc):
Handler <function builder_inited_handler at 0x7f7f61a03380> for event 'builder-inited' threw an exception (exception: [Errno 2] No such file or directory: 'tox')
make: *** [Makefile:20: latexpdf] Error 1

Expected result
A PDF or HTML file.
Related resources
No response

**Comment by marek22k** [comment]
Thanks for the answer! Which package is `toc` from? Unfortunately I couldn't find anything on the Internet.

**Comment by guedou** [comment]
It is "tox", from https://tox.wiki/

You can also check https://scapy.readthedocs.io/en/latest/installation.html#build-the-documentation-offline
