### ISSUE TITLE
DNS packet building does not always give the original result

### ISSUE THREAD

**Issue by LRGH** [secdev/scapy#4457]
### Brief description

When raw_packet_cache is disabled, p.build() does not return the original raw packet.

### Scapy version

2.3.2 to 2.6.0rc1

### Python version

all

### Operating system

all

### How to reproduce

```
s = b'\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x07bonjour\x05local\x00\x00\x01\x00\x01\xc0\x0c\x00\x1c\x00\x01'
p = DNS(s)
assert s == p.build()
p.clear_cache()
assert s == p.build()
```

NB: I found this issue by running scapy regression tests with packet cache disabled. I causes a regression in answering machines.

### Actual result

```
    assert s == p.build()
           ^^^^^^^^^^^^^^
AssertionError
```

### Expected result

There should not be any assertion error.

**Comment by gpotter2** [comment]
This is known, and by design. We chose to decompress DNS packets and store its values uncompressed, as changing any field would otherwise make an invalid DNS packet.

You can use `dns_compress()` if you want to compress the DNS packet in a form close to what you received in the first place.

When some sort of compression occurs, I would argue that it generally makes little sense to expect to be able to tweak just a single field and build a packet close to the original.

**Comment by LRGH** [comment]
Does it mean that it is expected that `clear_cache` can change the behaviour of `build`, or is it specific to DNS packets?
The semantics of `clear_cache` are unclear for me.

**Comment by guedou** [comment]
DNS is a specific case where the internal Scapy representation of fields could be different from the wire version due to compression. I don't think that clearing the cache breaks other protocols.

When the cache was not used, it was never possible to sent back the same DNS packet as Scapy received. This was not a nice behavior.

**Comment by LRGH** [comment]
Would it be useful if I start working on another implementation of DNS that would store the packets without decompressing them, and that would decompress only if needed when fields are changed?
The idea would be, when parsing a DNS packet, to mark all fields that are referred by pointers, and to have any2i trigger decompression either when a compressed or a marked field is modified.

Because the current representation of DNS packets can have counterintuitive consequences.
```
s = b'\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x07bonjour\x05local\x00\x00\x01\x00\x01\xc0\x0c\x00\x1c\x00\x01'
p = DNS(s)
assert s == p.build()
assert p.qd[1].qname == b'bonjour.local.'
p.qd[0].qname = b'hello.local.'
assert p.qd[1].qname == b'bonjour.local.'

p = DNS(s)
p.clear_cache()
assert s != p.build()
p.qd[0].qname = b'hello.local.'
assert p.qd[1].qname == b'bonjour.local.'

p = DNS(s)
p = dns_compress(p)
assert s == p.build()
p.qd[0].qname = b'hello.local.'
assert p.qd[1].qname == b'\xc0\x0c'

p = DNS(s)
p.clear_cache()
p = dns_compress(p)
assert s == p.build()
p.qd[0].qname = b'hello.local.'
assert p.qd[1].qname == b'\xc0\x0c'
```

**Comment by guedou** [comment]
Could you explain what is counterintuitive? This looks OK to me.

**Comment by LRGH** [comment]
Another counterintuitive behaviour below, which can be explained by looking at the internals:
```
s = b'\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x07bonjour\x05local\x00\x00\x01\x00\x01\xc0\x0c\x00\x1c\x00\x01'

assert DNSQR().qname == b'www.example.com.'

p = DNS(s)
p.qd[1] = DNSQR()
assert p.qd[1].qname == b'bonjour.local.'

p = DNS(s)
p.qd = [p.qd[0], DNSQR()]
assert p.qd[1].qname == b'www.example.com.'
```

**Comment by guedou** [comment]
I agree that users should easily know what value Scapy will return. I wonder if DNS compression isn't a special case. We might want to consider using `raw()` on fields, such as `raw(p[IPv6].dst)` returns the bytes of the field, while `p[IPv6].dst` returns the human version.

**Comment by LRGH** [comment]
Would it be interesting that I start an implementation of DNS that fulfills my requirements?
NB: I don't use DNS, so it would only be for the community, that's why I ask if there is a need.

My requirements would be:
- human-readable display shows if the field is compressed (i.e. ends with a pointer)
- if a packet is not modified it is built identical as when dissected
- works also if raw packet cache is disabled
- if a field is changed, it can be given either an uncompressed or a compressed value, which can be invalid
- invalid compressed values are the ones that point outside of the packet, or that generate infinite loops (NB: it is unclear for me if the RFC accepts pointers that point to compressed values, I would say no because it is worded "pointer to a prior occurance of the same name"; do you know if this happens in real network captures?)
- one or all compressed fields can be replaced by their uncompressed values

I have at least one question, which depends on what you think that users would expect: if a DNS packet has A with some string value and AAAA with a pointer to A, would a scapy user expect that if we change A then the value of AAAA changes too (and therefore stays a pointer) or that the value of AAAA does not change (and becomes uncompressed).
I would think the first option, especially if the human-readable display shows that the field is compressed, because it makes sense that those values are related one with the other.

**Comment by guedou** [comment]
I am unsure if specific changes are needed for the DNS layer, but I like some of your ideas:- the display of whether a  name was compressed in the original packet- the possibility to set malformed compressed namesConcerning A and AAAA with compressed names, I would expect that the name used in the AAAA RR does not change when the name in the A RR is changed to a different value.Sent from my iPhoneOn 21 Jul 2024, at 20:36, Louis Granboulan ***@***.***> wrote:﻿
Would it be interesting that I start an implementation of DNS that fulfills my requirements?
NB: I don't use DNS, so it would only be for the community, that's why I ask if there is a need.
My requirements would be:

human-readable display shows if the field is compressed (i.e. ends with a pointer)
if a packet is not modified it is built identical as when dissected
works also if raw packet cache is disabled
if a field is changed, it can be given either an uncompressed or a compressed value, which can be invalid
invalid compressed values are the ones that point outside of the packet, or that generate infinite loops (NB: it is unclear for me if the RFC accepts pointers that point to compressed values, I would say no because it is worded "pointer to a prior occurance of the same name"; do you know if this happens in real network captures?)
one or all compressed fields can be replaced by their uncompressed values

I have at least one question, which depends on what you think that users would expect: if a DNS packet has A with some string value and AAAA with a pointer to A, would a scapy user expect that if we change A then the value of AAAA changes too (and therefore stays a pointer) or that the value of AAAA does not change (and becomes uncompressed).
I would think the first option, especially if the human-readable display shows that the field is compressed, because it makes sense that those values are related one with the other.
