### ISSUE TITLE
Python Can issue in _recv_internal, socket.recv() is not working.

### ISSUE THREAD

**Issue by jim17** [secdev/scapy#4582]
> if `SocketsPool.multiplex_rx_packets()` is removed, `recv()` function is not receiving anything. 
> 
> Please add `SocketsPool.multiplex_rx_packets()` again. 

 _Originally posted by @jim17 in [16e52b1](https://github.com/secdev/scapy/commit/16e52b19dae3c36212d4056d58da8865ab94c44d#r148740754)_

**Comment by jim17** [comment]
Issue is fixed if _recv_internal is remapped to _recv_internal_fix.

![image](https://github.com/user-attachments/assets/961c29a0-9381-496c-b165-44a53fb70bc0)

**Comment by polybassa** [comment]
Thanks for this issue. Can you please provide a "test-code" to reproduce the issue?

**Comment by jim17** [comment]
Hi, @polybassa, in my second comment there's a snippet of code used to test the issue. In scapy release 2.5.0 no errors in recv observed.

**Comment by gpotter2** [comment]
Hi @jim17.

- Please fill the issue template that Scapy's issue come with. As-is, your issue is incomprehensible and a waste of our time, even if it's indeed a real bug
- Clearly this is one of the first questions you're asking on public forum. You should know that posting an **image** of code is considered extremely rude. Do you expect any of us to re-type every word of it to help you debug it?

Feel free to open another issue, having properly filed the template, if you still want this investigated.

**Comment by jim17** [comment]
Hi @gpotter2,

I do agree on placing the snippet of code and filling the template (I was in a hurry and prioritized informing about the issue).

As I provided the fix in the image I though it would be a short and quick discussion. If I have time, I'll try opening a new issue using the template you mentioned.

BR,
Miguel.
