### ISSUE TITLE
Accessing fields of a layer given by a user

### ISSUE THREAD

**Issue by THE4W350M3R00T** [secdev/scapy#740]
Hi everyone,

I was working on a application today which would take a packet then ask the user for a layer and a field
and then print the value of the field
so i did:
layer = raw_input('Layer: ')
field = raw_input('Field: ')
i know i can get the layer with pkt[layer]
but when i would do pkt[layer].field it would say AttributeError because it wouldnt search for the Content of field but for the Name field
so my issue is how can i select a field given by a user from a packet in scapy?
Thanks in advance

**Comment by Crossfire55555** [comment]
Yeah I was getting the same error when I ran some test cases. Its weird because I was running through pdb and __getattr__() was never explicitly called yet it is run looking for the name of the variable. Does anyone know where the command line functions are held? my guess is that it takes the attr in as a string.

**Comment by gpotter2** [comment]
Use
`getattr(pkt[layer], field)`

We handle the logic behind that
