### ISSUE TITLE
Sockets are always beeing closed

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#841]
In `sendrecv.py`, we are always closing the sockets after use. This can result in strange behaviors:

```
>>> a = conf.L2socket()
>>> send(IP(), socket=a) # Works but closes socket at the end
>>> send(IP(), socket=a) # Fails
WindowsError: exception.....
```

**Comment by Esser420** [comment]
I don't think this is a bug.

Isn't it more correct to use `a.send(IP())` in this case?

**Comment by stryngs** [comment]
If I'm correct, and I very well could be wrong; the original idea behind opening and closing a socket for each send or sendp was very intentional.  I myself was interested in this a while back and came across the following:
https://byt3bl33d3r.github.io/mad-max-scapy-improving-scapys-packet-sending-performance.html

I used his idea when it came to sendp() and there were some issues I cannot remember.  It's probably due to my being a novice at the deeper level stuff with Python.  Either way, if it is possible to speed up sending of frames/packets, that would be a welcome addition, especially for things like when scapy is used to inject and try to "win the race" ala TCP session hijacking, etc...  Things where speed matters, etc.

**Comment by guedou** [comment]
If someone feels like adding speed tricks to Scapy documentation, there are some useful  ideas in this gist: https://gist.github.com/guedou/d053b7bde0bc2fd79236
