### ISSUE TITLE
Bluetooth Scapy - Configuration Request gets always Command Rejected

### ISSUE THREAD

**Issue by marcinguy** [secdev/scapy#864]
Hi,

Trying to send a Bluetooth L2CAP Configuration Request using Scapy. Unfortunately, I always get Command Rejected.

Anybody has ideas why? What should be the correct way to do this using Scapy?

More info here on SO:

https://stackoverflow.com/questions/46551515/bluetooth-scapy-configuration-request-gets-always-command-rejected

Thanks,

**Comment by NadSo** [comment]
Hi Marcinguy,

Did you solve your problem? Are you working on BLE or bluetooth classic? I want to fuzz the BLE stack using the scapy's fuzz function but I don't know how to process. I am able to establish connection between two BLE device (master and slave) using the tool: 
https://github.com/mikeryan/PyBT
but I don't know how to send malformed data packet in order to fuzz the ATT/GATT Layer
Can you please help me?

**Comment by gpotter2** [comment]
@NadSo Hi,

I have no idea of how PyBT is working, therefore  I'm not sure to understand what you are looking for...

If you are willing to send Bluetooth data using scapy, I would recommend you to have a look at the SuperSocket classes in `scapy.layers.bluetooth`. You may want to create one then use its ˋsend` function with a packet.

Also, it can be a good idea to get the latest version of scapy from this github repository (Bluetooth module has been changed quite a lot).

Feel free to open an issue if you encounter any problems !

Have a good day

**Comment by NadSo** [comment]
Hello gpotter2,

thanks for your reply. Do you know how I can use the scapy's fuzz() function to fuzz the BLE Stack? I mean by that sending malformed data packet to BLE device

**Comment by marcinguy** [comment]
FYI I got my issues resolved. Was not a problem of Scapy. Configure Request was simply not allowed in this state.

**Comment by NadSo** [comment]
Hi marcinguy,

can you please answer me the other questions I asked? What about fuzzing?

**Comment by gpotter2** [comment]
@NadSo Do you have any code by now? What is "the BLE stack" ?

Scapy may fuzz packets which means you need to craft one before fuzzing it, then sending it

**Comment by NadSo** [comment]
@gpotter2 I have this code for example:

from PyBT import gatt
from PyBT import roles
from PyBT import gattclient
import argparse
from PyBT.roles import LE_Central
from PyBT.gatt_core import Connection

from threading import Thread
import gevent
import code
from PyBT.gattclient import runsource_with_connection

#from PyBT.att import ATT_Protocol
from PyBT import att
from PyBT import stack

from scapy.layers.bluetooth import  HCI_Cmd_LE_Create_Connection

def _argparser():
    parser = argparse.ArgumentParser(description='Gatt Client')
    parser.add_argument('-i', '--interface', dest='interface', action='store',
                        type=int, help='Interface to use', default=0)
    return parser

def main():
    parser = _argparser()
    args = parser.parse_args()

    central = LE_Central(adapter=args.interface)

    connection = Connection(central)
    connection.start()

    central.stack.connect('F8:F0:05:F3:4F:D7', 0x0)
    print "connecting..."

    gevent.sleep(4)

if __name__ == '__main__':
   main()



I am able to connect to the BLE device with the address: F8:F0:05:F3:4F:D7. But I don't know how to send malformed data to it in order to fuzz it.

**Comment by NadSo** [comment]
"BLE Stack" means Bluetooth low energy protocol layer

**Comment by guedou** [comment]
Closing this issue as it is not clear how it is related to Scapy.
