### ISSUE TITLE
Beginner Contributions: Code Cleanup with flake8 and Other Tools

### ISSUE THREAD

**Issue by ajstein** [secdev/scapy#92]
I wanted to get involved with various FLOSS projects, and I started to review scapy after being introduced to it in a study group.

You mention in the legacy contribution guidelines there is a lot of legacy code not conforming to preferred PEP8 and other style constraints.  Is there any object to me submitting pull requests in this regard?

**Comment by p-l-** [comment]
Hi,

Thanks for your interest in Scapy!

As mentioned in the [contributing guidelines](../blob/master/CONTRIBUTING.md), it's important to maintain a clean commit & code history.

There is no point to make a PR just to comply to PEP8 (for example), since that would break the commit history (we use `git blame` a lot). We only enforce PEP8 compliance in new code when merging pull requests.

Also, that's not an interesting way to get involved: an automatic tool could make such changes, and that would not give you any knowledge or competencies about Scapy.

Hope this helps!
